# Generated by Django 3.2.3 on 2021-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=22)),
                ('dono', models.CharField(max_length=18)),
                ('tipo', models.CharField(max_length=25)),
                ('cartao', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14)),
                ('valor', models.CharField(max_length=13)),
                ('data', models.CharField(max_length=13)),
                ('hora', models.CharField(max_length=11)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
    ]
